### ISSUE TITLE
"lumina: lumen:  db error; please try again later.."

### ISSUE THREAD

**Issue by NasmMachineAssembly** [naim94a/lumen#103]
first time making a bug report so bear with me.

the database im trying to pull on is SoTGame_dump.exe (1,865,212KB).

I get this error whenever I try to pull metadata. I'm on IDA 7.7.220118 (Windows x64).

lumina: lumen:  db error; please try again later..

Command "LuminaPullAllMds" failed

**Comment by AGG2017** [comment]
For me the right way to use this type of tools is to regularly backup the current database. It already happened to me to lost entire database and it was initialized by a blank one. I'm using the docker version under Linux as a lumina server for my Windows clients since the beginning for over 5 years and I found a need 2 times to restore the database from a backup for different reasons. So backups are essential part of the game.

**Comment by naim94a** [comment]
> For me the right way to use this type of tools is to regularly backup the current database. It already happened to me to lost entire database and it was initialized by a blank one. I'm using the docker version under Linux as a lumina server for my Windows clients since the beginning for over 5 years and I found a need 2 times to restore the database from a backup for different reasons. So backups are essential part of the game.

Sorry to hear about that. Hopefully the move to `diesel` will improve your experience with updates to the DB's schema in the future.
