### ISSUE TITLE
Could I use python scripts to automatically analyze lib files and upload to my lumen server?

### ISSUE THREAD

**Issue by breaking153** [naim94a/lumen#145]
i'm wondering cuz i found it is so hard to upload funcs in lib one by one

**Comment by breaking153** [comment]
but sadly i cannot found any func in python sdk about lumina server

**Comment by benjamindoron** [comment]
The best solution I've found is `idautils.ProcessUiActions("LuminaPushAllMds")`. Since it's UI interaction though, you can't just call `idc.qexit(0)` afterwards: testing shows that it doesn't actually execute the request. I've used AutoHotkey (and PowerShell and IDAPython) to actually automate this.

**Comment by breaking153** [comment]
> The best solution I've found is `idautils.ProcessUiActions("LuminaPushAllMds")`. Since it's UI interaction though, you can't just call `idc.qexit(0)` afterwards: testing shows that it doesn't actually execute the request. I've used AutoHotkey (and PowerShell and IDAPython) to actually automate this.

well i found it's possible to do such thing using idapython and Concurrence python module,i just extract it into a temp dir to analyze every obj file and it works
